// Person Action Type Constants
export const SET_ALL_PEOPLE = 'SET_ALL_PEOPLE'
export const SET_SINGLE_PERSON = 'SET_SINGLE_PERSON'
export const CREATE_PERSON = 'CREATE_PERSON'
export const UPDATE_PERSON = 'UPDATE_PERSON'
export const DELETE_PERSON = 'DELETE_PERSON'
export const ADD_FAVORITE_RESTAURANT = 'ADD_FAVORITE_RESTAURANT'
export const REMOVE_FAVORITE_RESTAURANT = 'REMOVE_FAVORITE_RESTAURANT'

export default {
  SET_ALL_PEOPLE,
  SET_SINGLE_PERSON,
  CREATE_PERSON,
  UPDATE_PERSON,
  DELETE_PERSON,
  ADD_FAVORITE_RESTAURANT,
  REMOVE_FAVORITE_RESTAURANT
}
